baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Code Examples'
pageRef = '/examples'
weight = 10

[[menus.main]]
name = 'Docs'
url = 'https://techdocs.akamai.com/edgeworkers/docs/welcome-to-edgeworkers?utm_content=docs'
weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
